cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'libgit2'
brew 'openssl'
brew 'readline'
brew 'unrar'
brew 'wget'
brew 'crystal'
brew 'rbenv'